version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ server
      - "15672:15672" # RabbitMQ management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  app:
    build: .
    container_name: payment-app
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
    environment:
      - NODE_ENV=production
      - RABBITMQ_URL=amqp://rabbitmq
